### ISSUE TITLE
Nvidia only?

### ISSUE THREAD

**Issue by lukakostic** [GPUPeople/cuRE#1]
So i watched the video and want to use this for rendering stuff with c++ but im wondering since it uses CUDA, does it only work on nvidia gpus? Could it be modified to use OpenMP / OpenCL / Something that works on all newer gpus ?

**Comment by michael-kenzel** [comment]
It requires support for CUDA compute capability 3.5 or newer. Yes, that basically means it works only on NVIDIA GPUs. Our existing implementation here quite heavily relies on CUDA. All pipeline code is written in CUDA C++ and makes heavy use of modern C++ features and templates. We also use inline PTX assembly here and there. And the existing build system is built around the NVIDIA CUDA toolchain. So, unfortunately, it won't be done by simply modifying some part of the code in some way. However, it would most likely be possible to reimplement the whole thing based on OpenCL, Direct3D/OpenGL/Vulkan Compute Shaders, or whatever other compute platform one might choose…
